//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int clientNo { get; set; }
        public string cName { get; set; }
    }
}
